version: "2.2"
services:
  iris:
    init: true
    image: intersystemscommunity/pexdemo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9980:9980
      - 52773:52773
      - 51773:1972
      - 55555:55555
